### ISSUE TITLE
Node takes to long to download files

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/node#48]
Check why the node takes to long to serve files when calling the access/download endpoints

- [x] @ramya-nevermined  Update https://node.mumbai.public.nevermined.network/ to version 0.4.1. Please take a look at the description of the pr https://github.com/nevermined-io/node/pull/50 for the changes needed in the configuration of the gateway
- [ ] @ialberquilla test to see if version `0.4.1` of the node fixes the filecoin download problems

**Comment by ialberquilla** [comment]
Testing it with cli version 0.8.0 still takes loo long 

![image](https://user-images.githubusercontent.com/974720/203036922-c85d2fa9-cef1-48e5-9f35-c9db138c1869.png)

![image](https://user-images.githubusercontent.com/974720/203036980-00268d9a-bac9-4a73-b8fb-7573f464dc6e.png)
